name: Tic-Tac-Toe CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # Adjust to match your .NET version

    - name: Restore NuGet packages
      run: dotnet restore "${{ github.workspace }}/TicTacToe-Project/TicTacToe.sln"

    - name: Build
      run: dotnet build "${{ github.workspace }}/TicTacToe-Project/TicTacToe.sln" --configuration Release

    - name: Run tests
      run: dotnet test "${{ github.workspace }}/TicTacToe-Project/TicTacToe.sln" --configuration Release --no-build

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          **/bin/Release/**
