name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a timeout for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y g++

    - name: Build C++ code
      run: g++ -o oop oop.cpp

    - name: Add debugging step
      run: echo "Running C++ code..."

    - name: Run C++ code
      run: ./oop
