name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        cd path/to/your/project  # Change directory to where your configure script is located
        ./configure  # Adjust the path if necessary
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
