name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y g++

    - name: Build C++ code
      run: g++ -o oop oop.cpp

    - name: Run C++ code
      run: ./oop
