name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        cd $GITHUB_WORKSPACE  # Change directory to the root of your repository
        ./configure  # Assuming configure script is in the root or a known subdirectory
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
